name: Feature Request
description: Suggest an idea for the project
title: "[Feature]: "
labels: ["enhancement"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Apps
        - Packages
        - Services
        - Database
        - Infra
        - Docs
        - Tools
        - CI/CD
    validations:
      required: true
